### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by princemaple** [wyeworks/elixir_console#76]
`Enum.reduce([1,2,3,4,5], &Kernel.+/2)` should work but doesn't.

```
invalid args for &, expected an expression in the format of &Mod.fun/arity, &local/arity or a capture containing at least one arg
ument as &1
```

Even the error message says it's allowed. And it indeed works in IEx.

**Comment by jmbejar** [comment]
@princemaple Thanks for reporting. We're currently working on fixing this issue.
